# Generated by Django 2.2 on 2019-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitewide_notice', models.CharField(max_length=150, verbose_name='Sitewide Notice')),
            ],
        ),
        migrations.DeleteModel(
            name='SitewideNotice',
        ),
    ]
