# Generated by Django 2.0.2 on 2018-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('firewood_type', models.CharField(choices=[(1, 'Blandat lövträd'), (2, 'Björkved'), (3, 'Bokved'), (4, 'Askved')], default=1, max_length=50)),
                ('firewood_choice', models.CharField(max_length=50)),
            ],
        ),
    ]
