# Generated by Django 2.0.2 on 2018-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0005_auto_20180302_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Hämta på plats', 'Hämta på plats')], default=1, max_length=50),
        ),
    ]
