# Generated by Django 2.0.2 on 2018-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0007_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(1, 'Ej påbörjad'), (2, 'Påbörjad'), (3, 'Levererad')], default=1, max_length=30, verbose_name='Status på order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Hämta på plats', 'Hämta på plats')], default=1, max_length=50, verbose_name='Val av leverans'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Beskrivning'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-post'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firewood_choice',
            field=models.CharField(max_length=50, verbose_name='Val av ved'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firewood_quantity',
            field=models.CharField(default=1, max_length=50, verbose_name='Kvantitet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Namn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('Blandat lövträd', 'Blandat lövträd'), ('Björkved', 'Björkved'), ('Bokved', 'Bokved'), ('Askved', 'Askved'), ('Övrigt', 'Övrigt')], default=1, max_length=50, verbose_name='Produkttyp'),
        ),
    ]
