# Generated by Django 2.0.2 on 2018-03-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0008_auto_20180302_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Ej påbörjad', 'Ej påbörjad'), ('Påbörjad', 'Påbörjad'), ('Levererad', 'Levererad')], default=1, max_length=30, verbose_name='Status på order'),
        ),
    ]
