# Generated by Django 2.0.2 on 2018-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0013_auto_20180304_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='-', max_length=50, verbose_name='Leveransadress (om valet är utkörning)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Hämta på plats', 'Hämta på plats'), ('Utkörning', 'Utkörning')], default=1, max_length=50, verbose_name='Val av leverans'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Kvantitet (pall/kubik)'),
        ),
    ]
