# Generated by Django 2.0.2 on 2018-03-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0014_auto_20180309_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Leveransadress (om valet är utkörning)'),
        ),
    ]
