# Generated by Django 2.0.2 on 2018-03-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0015_auto_20180309_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Namn på erbjudande')),
                ('offer_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
