# Generated by Django 2.0.2 on 2018-03-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0016_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Kontant', 'Kontant'), ('Swish', 'Swish'), ('Kort', 'Kort'), ('Faktura', 'Faktura')], default='Kontant', max_length=50, verbose_name='Betala med'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Kvantitet (kubik)'),
        ),
    ]
