# Generated by Django 2.0.2 on 2018-03-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0017_auto_20180310_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Övrig info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Kvantitet (kubik/st)'),
        ),
    ]
