# Generated by Django 2.0.2 on 2018-03-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0018_auto_20180310_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Erbjudande', 'verbose_name_plural': 'Erbjudanden'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Ordrar'},
        ),
    ]
