# Generated by Django 2.2 on 2019-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0019_auto_20180314_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Produktnamn')),
                ('desc', models.TextField(blank=True, max_length=1000, verbose_name='Beskrivning')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('Blandat lövträd', 'Blandat lövträd'), ('Björkved', 'Björkved'), ('Bokved', 'Bokved'), ('Askved', 'Askved'), ('Övrigt', 'Övrigt')], default=1, max_length=50, verbose_name='Produkttyp')),
            ],
        ),
    ]
