# Generated by Django 2.2 on 2019-04-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ved', '0022_auto_20190419_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Delivery Address (if choice is delivery)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Hämta på plats', 'Hämta på plats'), ('Utkörning', 'Utkörning')], default=1, max_length=50, verbose_name='Delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Other Info'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firewood_choice',
            field=models.CharField(max_length=50, verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Delivered', 'Delivered')], default='Not Started', max_length=30, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Swish', 'Swish'), ('Card', 'Card'), ('Invoice', 'Invoice')], default='Cash', max_length=50, verbose_name='Pay With'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_type',
            field=models.CharField(choices=[('Blandat lövträd', 'Blandat lövträd'), ('Björkved', 'Björkved'), ('Bokved', 'Bokved'), ('Askved', 'Askved'), ('Övrigt', 'Övrigt')], default=1, max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity (cubic/piece)'),
        ),
    ]
